// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using DatabaseService.Models;

#nullable disable

namespace DatabaseService.Context
{
    public partial class IndeklimaContext : DbContext
    {
        public IndeklimaContext()
        {
        }

        public IndeklimaContext(DbContextOptions<IndeklimaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Temperatur> Temperatur { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Temperatur>(entity =>
            {
                entity.HasKey(e => new { e.Dato, e.Tidspunkt })
                    .HasName("PK__Temperat__DAF567423CA3787A");

                entity.Property(e => e.Dato)
                    .HasColumnType("date")
                    .HasColumnName("dato");

                entity.Property(e => e.Tidspunkt)
                    .HasColumnType("time(0)")
                    .HasColumnName("tidspunkt");

                entity.Property(e => e.Grader)
                    .HasColumnType("numeric(3, 1)")
                    .HasColumnName("grader");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}