// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatabaseService.Models
{
    public partial class Temperatur
    {
        public DateTime Dato { get; set; }
        public TimeSpan Tidspunkt { get; set; }
        public decimal Grader { get; set; }
    }
}